# Generated by Django 5.2.3 on 2025-07-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=32)),
                ('reading', models.CharField(blank=True, max_length=64)),
                ('meaning', models.TextField(blank=True)),
                ('mode', models.CharField(max_length=10)),
                ('font', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
