# Generated by Django 5.2.3 on 2025-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jan_code',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
