# Generated by Django 5.2.3 on 2025-07-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_order_jan_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TshirtSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_choices', models.JSONField(default=list)),
                ('body_color_choices', models.JSONField(default=list)),
                ('text_color_choices', models.JSONField(default=list)),
                ('price', models.PositiveIntegerField(default=3000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='body_color',
            field=models.CharField(default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='L', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='text_color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
