# Generated by Django 5.2.3 on 2025-07-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_tshirtsetting_order_body_color_order_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True)),
                ('kanji', models.CharField(max_length=32)),
                ('reading', models.CharField(max_length=64)),
                ('meaning', models.TextField()),
                ('mode', models.CharField(max_length=10)),
                ('font', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=32)),
                ('body_color', models.CharField(max_length=20)),
                ('text_color', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tshirtsetting',
            name='price',
            field=models.PositiveIntegerField(default=5500),
        ),
    ]
