# Generated by Django 5.2.3 on 2025-07-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_printjob_alter_tshirtsetting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjiateji',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_it',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_th',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kanjiateji',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_de',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_en',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_es',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_fr',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_it',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_ja',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_ko',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_nl',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_ru',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_sv',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_th',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_zh_hans',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='body_color_zh_hant',
            field=models.CharField(default='white', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_it',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_ko',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_nl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_sv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_th',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='font_zh_hant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_de',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_es',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_fr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_it',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_ja',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_ko',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_nl',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_sv',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_th',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_zh_hans',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kanji_zh_hant',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meaning_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_de',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_es',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_fr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_it',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_ja',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_ko',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_nl',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_sv',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_th',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_zh_hans',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_zh_hant',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_de',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_en',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_es',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_fr',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_it',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_ja',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_ko',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_nl',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_ru',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_sv',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_th',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_zh_hans',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reading_zh_hant',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_de',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_es',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_fr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_it',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_ja',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_ko',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_nl',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_sv',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_th',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_zh_hans',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size_zh_hant',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_de',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_en',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_es',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_fr',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_it',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_ja',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_ko',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_nl',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_ru',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_sv',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_th',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_zh_hans',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_color_zh_hant',
            field=models.CharField(default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_de',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_es',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_fr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_it',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_ja',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_ko',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_nl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_sv',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_th',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_zh_hans',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='body_color_zh_hant',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_it',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_ko',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_nl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_sv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_th',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='font_zh_hant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_de',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_es',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_fr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_it',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_ja',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_ko',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_nl',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_sv',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_th',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_zh_hans',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kanji_zh_hant',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='meaning_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_de',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_es',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_fr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_it',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_ja',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_ko',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_nl',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_sv',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_th',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_zh_hans',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='mode_zh_hant',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_de',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_es',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_fr',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_it',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_ja',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_ko',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_nl',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_sv',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_th',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_zh_hans',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reading_zh_hant',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_de',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_es',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_fr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_it',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_ja',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_ko',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_nl',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_sv',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_th',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_zh_hans',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='size_zh_hant',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_de',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_es',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_fr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_it',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_ja',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_ko',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_nl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_sv',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_th',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_zh_hans',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='text_color_zh_hant',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
