# Generated by Django 5.2.3 on 2025-07-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_kanjiateji_name_de_kanjiateji_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_ja',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_ko',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_sv',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_th',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_zh_hans',
        ),
        migrations.RemoveField(
            model_name='kanjiateji',
            name='name_zh_hant',
        ),
    ]
