# Generated by Django 5.2.3 on 2025-08-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_remove_kanjiateji_name_de_remove_kanjiateji_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=10, unique=True, verbose_name='部品漢字')),
                ('meaning', models.CharField(blank=True, max_length=255, verbose_name='意味（多言語化）')),
            ],
        ),
    ]
