# Generated by Django 5.2.3 on 2025-08-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_kanjimeaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_ko',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_nl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_sv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='meaning_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='意味（多言語化）'),
        ),
    ]
