# Generated by Django 5.2.3 on 2025-08-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_kanjimeaning_meaning_de_kanjimeaning_meaning_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjiateji',
            name='meaning_parts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
