# Generated by Django 5.2.3 on 2025-08-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_kanjiateji_meaning_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirtsetting',
            name='jan_code_const',
            field=models.CharField(default='4901234567894', max_length=13),
        ),
    ]
