# Generated by Django 5.2.3 on 2025-08-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_tshirtsetting_jan_code_const'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(blank=True, default='internal', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
