# Generated by Django 5.2.3 on 2025-09-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_remove_kanjimeaning_meaning_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='order_no',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
