# Generated by Django 5.2.3 on 2025-09-22 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_alter_printjob_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
